dataset:
  num_classes: 65
  training:
    video_mp4_path: datasets/thumos14/validation/
    video_info_path: datasets/thumos_anno/val_video_info.csv
    video_anno_path: datasets/multithumos/multithumos_val_ours.csv
    video_data_path: datasets/thumos14/validation_npy/
    class_index_map: datasets/multithumos/class_list.txt
    # class_index_map: 'datasets/thumos_anno/Class Index_Detection.txt'
    clip_length: 256
    clip_stride: 30
    crop_size: 96
  testing:
    video_mp4_path: datasets/thumos14/test/
    video_info_path: datasets/thumos_anno/test_video_info.csv
    video_anno_path: datasets/multithumos/multithumos_test_ours.csv
    video_data_path: datasets/thumos14/test_npy/
    flow_data_path: datasets/thumos14/test_flow_npy/
    crop_size: 96
    clip_length: 256
    clip_stride: 128

model:
  in_channels: 3
  freeze_bn: true
  freeze_bn_affine: true
  backbone_model: ./models/i3d_models/rgb_imagenet.pt

training:
  batch_size: 1
  learning_rate: 1e-5
  weight_decay: 1e-3
  max_epoch: 25
  checkpoint_path: ./models/multithumos14/
  random_seed: 2023
  focal_loss: true
  hidden_dim: 512
  num_queries: 126
  num_heads: 8

testing:
  conf_thresh: 0.01
  top_k: 5000
  nms_thresh: 0.5
  nms_sigma: 0.5
  checkpoint_path: models/thumos14_newbest/checkpoint_19.pth
  output_path: ./output
  output_json: detection_results_19.json
